### ISSUE TITLE
Improvement: TP to use SMF editor

### ISSUE THREAD

**Issue by Bopske** [Tinyportal/TinyPortal#972]
As suggested. Now we are dropping 2.0 support it is feasible to use the standard SMF 2.1 editor

**Comment by Bopske** [comment]
@tinoest , do you have any idea what we need to do to make this happen? Had a quick look at the smf code, but this is too complex for me to pick up...

**Comment by tinoest** [comment]
Does this help at all?

https://github.com/SimplePortal/SimplePortal/blob/c2577a4e2e072ceecffcd6168c145f9eb495f3fa/smf2/Sources/PortalAdminPages.php#L574

**Comment by Bopske** [comment]
No, not at all.

**Comment by tinoest** [comment]
Ok, it should be we include that file and then call that function I linked to and pass the editorOptions to it, then in the template reference the editor_id etc

the issue will probably be the custom left to right logic we added as editor options in the toolbar

**Comment by tinoest** [comment]
Had a look at this, I can get it to work for bbc (as we actually already use the builtin SMF editor for that) but I can't get it working for HTML.

**Comment by Bopske** [comment]
Hmm, I cannot help with this. What do you propose, leave it as it is?

**Comment by tinoest** [comment]
> Hmm, I cannot help with this. What do you propose, leave it as it is?

I decided to just use the BBCode logic https://github.com/tinoest/TinyPortal/tree/TPSMFSCeditor 

It loads it correctly, I am just not sure it's actually doing what we want it to do anymore... mainly as I can't remember what it used to do... it's been a while since I used TinyPortal.

Whilst it is nice to use their version and we probably should, I think what we have modified in it, makes it unrealistic.
